version: 2
jobs:
  build:
    working_directory: ~/QuickList/QuickList
    
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - run: mvn dependency:go-offline # gets the project dependencies
      
      
